## 1. 常数张量与变量

In [1]:
import tensorflow as tf

### 1.1 张量

In [2]:
x = tf.ones(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [3]:
x = tf.zeros(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [4]:
x = tf.random.normal(shape=(3,1), mean=0, stddev=1)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 1.0107975],
       [ 1.486004 ],
       [-2.297776 ]], dtype=float32)>

In [5]:
x = tf.random.uniform(shape=(3,1), minval=0, maxval=1)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.1130861 ],
       [0.86464477],
       [0.6800699 ]], dtype=float32)>

Tensorflow张量是不可赋值的。